// <auto-generated />
using System;
using Chartify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chartify.Infrastructure.Migrations
{
    [DbContext(typeof(ChartifyDbContext))]
    [Migration("20260129183647_UpdateChartCompositeKey")]
    partial class UpdateChartCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chartify.Infrastructure.ChartEntries.ChartEntity", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("daily");

                    b.HasKey("Date", "Region");

                    b.HasIndex("Date");

                    b.HasIndex("Region");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("Chartify.Infrastructure.ChartEntries.ChartEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistNames")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("ChartDate")
                        .HasColumnType("date");

                    b.Property<string>("ChartRegion")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("Streams")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrackSpotifyId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TrackSpotifyId");

                    b.HasIndex("ChartDate", "ChartRegion");

                    b.ToTable("ChartEntries");
                });

            modelBuilder.Entity("Chartify.Infrastructure.ChartEntries.ChartEntryEntity", b =>
                {
                    b.HasOne("Chartify.Infrastructure.ChartEntries.ChartEntity", "Chart")
                        .WithMany("Entries")
                        .HasForeignKey("ChartDate", "ChartRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chart");
                });

            modelBuilder.Entity("Chartify.Infrastructure.ChartEntries.ChartEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
